apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: test-build-github
spec:
  workspaces:
    - name: output
      description: "Directorio donde se descargará el repositorio"
  params:
    - name: url
      type: string
      description: "URL del repositorio GitHub"
    - name: revision
      type: string
      default: "main"
      description: "Rama a clonar"
  steps:
    - name: clone
      image: alpine/git:latest
      workingDir: $(workspaces.output.path)
      script: |
        #!/usr/bin/env sh
        set -e
        echo "=== Clonando $(params.url) rama $(params.revision) ==="
        rm -rf ./* ./.[!.]*
        git clone --depth 1 -b $(params.revision) $(params.url) .
        echo "=== Repositorio descargado en el Workspace ==="
        ls -la
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-from-git
  namespace: test-build-github
spec:
  params:
    - name: IMAGE_NAME
      type: string
      default: "app-php"
    - name: IMAGE_TAG
      type: string
      default: "v1.0.0"
  workspaces:
    - name: source
      description: "Workspace compartido donde reside el repositorio"
  volumes:
    - name: pipeline-token-vol
      secret:
        secretName: pipeline-token-manual
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: pipeline-token-vol
          mountPath: /var/run/custom-token
          readOnly: true
      workingDir: $(workspaces.source.path)/tekton/codigo
      script: |
        #!/usr/bin/env bash
        set -e

        DEST="image-registry.openshift-image-registry.svc:5000/test-build-github/$(params.IMAGE_NAME):$(params.IMAGE_TAG)"

        echo "=== Directorio de compilación: $(pwd) ==="
        ls -la

        echo "=== Compilando imagen con Buildah ==="
        buildah bud --tls-verify=false -t "${DEST}" .

        echo "=== Obteniendo token estático de 365 días ==="
        TOKEN=$(cat /var/run/custom-token/token)

        echo "=== Subiendo imagen al Registry interno en test-build-github ==="
        buildah push --tls-verify=false --creds="pipeline:${TOKEN}" "${DEST}"
