## Configuración global
option domain-name "ilba.cat";
option domain-name-servers 10.26.0.5; # IP del Bastión (DNS)

default-lease-time 600;
max-lease-time 7200;
authoritative;

# Red aislada de OKD
subnet 10.26.0.0 netmask 255.255.255.0 {
    range 10.26.0.150 10.26.0.200; # Rango dinámico para dinámicas temporales
    option routers 10.26.0.1;      # Gateway (MikroTik)

    # --- RESERVAS ESTÁTICAS DE OKD ---

    # Bootstrap
    host bootstrap {
        hardware ethernet 00:50:56:93:0f:e3;
        fixed-address 10.26.0.10;
        option host-name "bootstrap.ilba.cat";
    }

    # Masters
    host master1 {
        hardware ethernet 00:50:56:93:93:09;
        fixed-address 10.26.0.11;
        option host-name "master1.ilba.cat";
    }

    host master2 {
        hardware ethernet 00:50:56:93:84:7a;
        fixed-address 10.26.0.12;
        option host-name "master2.ilba.cat";
    }

    host master3 {
        hardware ethernet 00:50:56:93:8e:6b;
        fixed-address 10.26.0.13;
        option host-name "master3.ilba.cat";
    }

    # Workers
    host worker1 {
        hardware ethernet 00:50:56:93:6b:88;
        fixed-address 10.26.0.21;
        option host-name "worker1.ilba.cat";
    }

    host worker2 {
        hardware ethernet 00:50:56:93:55:4b;
        fixed-address 10.26.0.22;
        option host-name "worker2.ilba.cat";
    }
}
